name: Test Suite

on:
  # Controls when the action will be triggered.
  push:           # A push to any branch.
  pull_request:   # A pull request to the trunk (main/master branch).
    branches: [ trunk ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  php-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php: '7.4'
          - php: '8.0'

    # Steps represent a sequence of tasks that will be executed as part of the job
    name: "PHP${{ matrix.php }} ${{ matrix.composer-flags }}"
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          #  extensions: json
          #  ini-values: "post_max_size=256M" #optional
          coverage: pcov

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-

      - name: Update composer dependencies
        run: composer update -o --no-interaction --no-progress --prefer-dist ${{ matrix.composer-flags }}
        continue-on-error: ${{ matrix.allow_failure }}

      - name: Run TEST suite
        run: composer run-script test:ci -- -C
        continue-on-error: ${{ matrix.allow_failure }}

